INSERT INTO BANK_ACCOUNT(ID,BALANCE,OPEN_DATE,OWNER_ID) VALUES(1,10,NOW(),1);
INSERT INTO BANK_ACCOUNT(ID,BALANCE,OPEN_DATE,OWNER_ID) VALUES(2,20,NOW(),2);
ALTER SEQUENCE HIBERNATE_SEQUENCE RESTART WITH (SELECT MAX(ID)+1 FROM BANK_ACCOUNT);

insert into transaction(Id, amount, timestamp,destination_id, source_id, description) values (1,5,now(),1,2, 'Loan');
